name: CI Pipeline
on:
  workflow_call
jobs:
  test:
    name: Test Repository
    runs-on: ubuntu-latest
    container: ubuntu:latest
    permissions:
      contents: write
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3