name: CI Pipeline
description: "CI Pipeline"

runs:
  using: "composite"
  steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      shell: bash
    - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      shell: bash
    - name: List current directory
      run: |
        pwd
      shell: bash
    - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      shell: bash
    - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      shell: bash
    - run: echo "🎉 Github workspace is ${{ github.workspace }}"
      shell: bash
    - run: echo "🍏 This job's status is ${{ job.status }}."
      shell: bash
    - name: List files in the repository ${{ github.workspace }}
      run: |
        ls -la ${{ github.workspace }}
      shell: bash
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: clean test --info