name: CI Pipeline
on:
  workflow_call
jobs:
  test:
    name: Test Repository
    runs-on: ubuntu-latest
    container: ubuntu:latest
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List current directory
        run: |
          pwd
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: clean test --info